1 founding rio with gfo light
Onto-Med/RIO pull request #2
Opened 2024-09-05 16:07 UTC by AlexU75

2024-09-06 07:34 UTC, ChristophB approved these changes
I've created a pull request for the PURL entry https://github.com/perma-id/w3id.org/pull/4398

2024-09-06 11:30 UTC, KonradHoeffner requested changes
My suggested changes are in <https://github.com/Onto-Med/RIO/pull/5>.

2025-02-06 11:34 UTC, KonradHoeffner approved these changes

2025-02-11 12:59 UTC, KonradHoeffner approved these changes
Generally approve this PR, only minor nitpick is the line endings of rio.svg are Windows CRLF endings again, I would normalize this.

2025-02-11 13:11 UTC, ChristophB approved these changes

2025-02-11 14:31 UTC, merged